services:
  ad-dotnet-10-example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad-dotnet-10-example
    dns:
      - CHANGE_THIS_TO_YOUR_DNS_SERVER
    dns_search:
      - CHANGE_THIS_TO_YOUR_DNS_SEARCH
    environment:
      - AD_LDAP_HOST=CHANGE_THIS_TO_YOUR_AD_LDAP_HOST
      - KRB5_PRINCIPAL=HTTP/CHANGE_THIS_TO_YOUR_KRB5_PRINCIPAL
      - KRB5_KEYTAB_PATH=/etc/security/keytabs/service.keytab
    volumes:
      - ./ad-files/service.keytab:/etc/security/keytabs/service.keytab:ro
